version: '3'

services:
  upwork_test:
    restart: unless-stopped
    build: .
    ports:
      - "8099:80"
    container_name: upwork
    networks:
      - ortak-network
networks:
  ortak-network:
    external: true